dubbo:
  application:
    name: provider-ticket
  registry: #配置注册中心，用来发布提供者的服务
    address: zookeeper://192.168.0.109:2181
  protocol:
    port: 12398 #默认的端口号是20880，不与其它服务提供者的端口号重复
  scan:
    base-packages: com.weichuang.ticket.service #服务所在的包